// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/agent/v2/agent.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductAgent_ParseProducts_FullMethodName = "/agent.v2.ProductAgent/ParseProducts"
)

// ProductAgentClient is the client API for ProductAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// defining how Go REST API will communicate with Python AI agent over gRPC.
// takes in JSON blob (ProductRequest) and then returns structured ParsedProduct objects.
type ProductAgentClient interface {
	ParseProducts(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type productAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAgentClient(cc grpc.ClientConnInterface) ProductAgentClient {
	return &productAgentClient{cc}
}

func (c *productAgentClient) ParseProducts(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, ProductAgent_ParseProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAgentServer is the server API for ProductAgent service.
// All implementations must embed UnimplementedProductAgentServer
// for forward compatibility.
//
// defining how Go REST API will communicate with Python AI agent over gRPC.
// takes in JSON blob (ProductRequest) and then returns structured ParsedProduct objects.
type ProductAgentServer interface {
	ParseProducts(context.Context, *ProductRequest) (*ProductResponse, error)
	mustEmbedUnimplementedProductAgentServer()
}

// UnimplementedProductAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductAgentServer struct{}

func (UnimplementedProductAgentServer) ParseProducts(context.Context, *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseProducts not implemented")
}
func (UnimplementedProductAgentServer) mustEmbedUnimplementedProductAgentServer() {}
func (UnimplementedProductAgentServer) testEmbeddedByValue()                      {}

// UnsafeProductAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAgentServer will
// result in compilation errors.
type UnsafeProductAgentServer interface {
	mustEmbedUnimplementedProductAgentServer()
}

func RegisterProductAgentServer(s grpc.ServiceRegistrar, srv ProductAgentServer) {
	// If the following call pancis, it indicates UnimplementedProductAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductAgent_ServiceDesc, srv)
}

func _ProductAgent_ParseProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAgentServer).ParseProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAgent_ParseProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAgentServer).ParseProducts(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAgent_ServiceDesc is the grpc.ServiceDesc for ProductAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v2.ProductAgent",
	HandlerType: (*ProductAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseProducts",
			Handler:    _ProductAgent_ParseProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v2/agent.proto",
}
