# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/v1/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61gent/v1/agent.proto\x12\x08\x61gent.v1\"$\n\x0eProductRequest\x12\x12\n\njson_input\x18\x01 \x01(\t\"<\n\x0fProductResponse\x12)\n\x08products\x18\x01 \x03(\x0b\x32\x17.agent.v1.ParsedProduct\"\x81\x01\n\rParsedProduct\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tthumbnail\x18\x03 \x01(\t\x12\x13\n\x0bingredients\x18\x04 \x03(\t\x12%\n\tretailers\x18\x05 \x03(\x0b\x32\x12.agent.v1.Retailer\"W\n\x08Retailer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x01\x12\r\n\x05price\x18\x04 \x01(\t\x12\x10\n\x08in_stock\x18\x05 \x01(\x08\x32T\n\x0cProductAgent\x12\x44\n\rParseProducts\x12\x18.agent.v1.ProductRequest\x1a\x19.agent.v1.ProductResponseB\nZ\x08\x61gent/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010agent/v1'
  _globals['_PRODUCTREQUEST']._serialized_start=34
  _globals['_PRODUCTREQUEST']._serialized_end=70
  _globals['_PRODUCTRESPONSE']._serialized_start=72
  _globals['_PRODUCTRESPONSE']._serialized_end=132
  _globals['_PARSEDPRODUCT']._serialized_start=135
  _globals['_PARSEDPRODUCT']._serialized_end=264
  _globals['_RETAILER']._serialized_start=266
  _globals['_RETAILER']._serialized_end=353
  _globals['_PRODUCTAGENT']._serialized_start=355
  _globals['_PRODUCTAGENT']._serialized_end=439
# @@protoc_insertion_point(module_scope)
